/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ContentBox = () => {
  return (
    <article className="flex flex-col py-px mt-52 w-full bg-white rounded-xl border border-black border-solid max-md:mt-10 max-md:max-w-full">
      <header className="flex flex-wrap gap-6 px-5 py-1 text-4xl text-white whitespace-nowrap bg-emerald-900 border border-black border-solid">
        <div
          className="flex shrink-0 bg-red-300 rounded-full border border-black border-solid h-[54px] w-[54px]"
          role="img"
          aria-label="Profile icon"
        />
        <h2 className="flex-auto self-start border border-black border-solid w-[1234px] max-md:max-w-full">
          Lund
        </h2>
      </header>
      <div className="flex flex-col items-start gap-8 mt-4 ml-5">
        <div
          className="shrink-0 max-w-full bg-sky-900 rounded-3xl border border-black border-solid h-[68px] w-[486px]"
          role="button"
          tabIndex="0"
          aria-label="Action button 1"
        />
        <div
          className="shrink-0 self-end mr-7 max-w-full bg-sky-900 rounded-3xl border border-black border-solid h-[68px] w-[788px] max-md:mr-2.5"
          role="button"
          tabIndex="0"
          aria-label="Action button 2"
        />
        <div
          className="shrink-0 max-w-full bg-sky-900 rounded-3xl border border-black border-solid h-[68px] w-[788px]"
          role="button"
          tabIndex="0"
          aria-label="Action button 3"
        />
      </div>
      <div className="flex flex-col self-end mt-8 mr-7 w-full max-w-[1079px] max-md:mr-2.5 max-md:max-w-full">
        <div
          className="shrink-0 self-end max-w-full bg-sky-900 rounded-3xl border border-black border-solid h-[68px] w-[566px]"
          role="button"
          tabIndex="0"
          aria-label="Action button 4"
        />
        <div
          className="shrink-0 mt-60 max-w-full bg-emerald-900 rounded-3xl h-[69px] w-[851px] max-md:mt-10"
          role="button"
          tabIndex="0"
          aria-label="Action button 5"
        />
      </div>
    </article>
  );
};

export default ContentBox;
